# Default values for Keirox Helm Chart.
# This is a YAML-formatted file.

replicaCount: 3

image:
  repository: keirox/keirox
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "keirox-cluster"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"
  prometheus.io/path: "/metrics"

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - name: kafka-gateway
      port: 9092
      targetPort: 9092
    - name: arrow-flight
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9090
      targetPort: 9090
    - name: raft-consensus
      port: 9091
      targetPort: 9091

ingress:
  enabled: false

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "8"
    memory: "16Gi"

persistence:
  enabled: true
  storageClass: "io1"
  accessMode: ReadWriteOnce
  size: 500Gi
  mountPath: /var/lib/keirox/data

env:
  - name: KEIROX_ENVIRONMENT
    value: "production"
  - name: RUST_LOG
    value: "info"
  - name: KEIROX_S3_BUCKET
    value: "keirox-tier1-storage"
  - name: KEIROX_KMS_PROVIDER
    value: "aws-kms"
